# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Krish Desai"
title_separator          : "-"
baseurl                  : ""
name                     : &name "Krish Desai, PhD"
description              : &description "Machine Learning Researcher"
url                      : "https://www.desai.ml"
repository               : "krishdesai7/krishdesai7.github.io"

author:
  avatar           : "assets/images/profile.png"
  name             : "Krish Desai, PhD"
  bio              : "Machine Learning Researcher"
  location         : "Berkeley, California"
  employer         : "Lawrence Berkeley National Lab"
  uri              : "https://www.desai.ml" # URL
  email            : "krishdesai7@gmail.com" 

  academia         : # URL
  arxiv            : "desai_k_1"
  googlescholar    : "StYT3XIAAAAJ"
  inspirehep       : "1987978"
  orcid            : "0000-0003-2559-8910"
  semantic         : "1885318652"
  pubmed           : # "https://pubmed.ncbi.nlm.nih.gov/?term=desai+krish"
  researchgate     : "Krish-Desai"
  scopus           : # URL

  bitbucket        : # Username
  github           : "@krishdesai7"
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  bluesky          : "@h4h5.bsky.social"
  instagram        : "@krishdesai7"
  linkedin         : "krish-desai"
  twitter          : "@krishdesai7"
  wikipedia        : # Username
  youtube          : # Username

# Publication Categories
publication_category:
  theses:
    title: 'Theses'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'
  preprints:
    title: 'Preprints'

# SEO
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :
twitter.username         : "krishdesai7"

# Analytics
analytics:
  provider: "google-analytics-4"
  google:
    tracking_id: "G-RMHJJ7H3MC"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# These settings control the types of collections used by the template
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  experience:
    output: true
    permalink: /:collection/:path/

# These settings control how pages and collections are included in the site
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
  # _experience
  - scope:
      path: ""
      type: experience
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-redirect-from

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-redirect-from

category_archive:
  type: liquid
  path: /categories/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
